application/backend/app/application.py, application/backend/app/config.py, application/containers/development/Dockerfile.next-frontend, application/containers/development/docker-compose.yml, application/containers/development/nginx.conf, application/next-frontend/package.json
react frontend: port localhost:4434
next frontend : port localhost:4000
=> PB-14p: Docker nginx next frontend

application/backend/app/api/auth.py, application/backend/app/application.py, application/backend/app/auth/__init__.py, application/backend/app/config.py, application/frontend/src/api/httpClient.ts
Adds cookie based auth. Default config from flask_jwt_extended library
Uses double submit to protect agianst csrf : 
https://flask-jwt-extended.readthedocs.io/en/stable/token_locations.html#cookies
=> PB-17k: Cookie based auth

.github/workflows/backend.yml, .github/workflows/frontend.yml, .github/workflows/next-frontend.yml
Creates cached workflows for testing building frontends
=> feat(ci): adds gh actions for frontend

application/next-frontend/package-lock.json, application/next-frontend/package.json, application/next-frontend/pages/admin/index.tsx, application/next-frontend/src/Adminpage/scenarios/Home/components/CardComponent.tsx, application/next-frontend/src/Adminpage/scenarios/Home/components/ModalButton.tsx, application/next-frontend/src/Adminpage/scenarios/Home/context/ModelContext.tsx, application/next-frontend/src/Adminpage/scenarios/Home/index.tsx, application/next-frontend/src/Adminpage/scenarios/Home/scenarios/Events/index.tsx, application/next-frontend/src/Adminpage/scenarios/Home/scenarios/Events/scenarios/CreateEventCard.tsx, application/next-frontend/src/Adminpage/scenarios/Home/scenarios/Restaurants/index.tsx, application/next-frontend/src/Adminpage/scenarios/Home/scenarios/Restaurants/scenarios/NewRestaurantModal.tsx, application/next-frontend/src/Adminpage/scenarios/Home/scenarios/Users.tsx, application/next-frontend/src/Adminpage/scenarios/Navbar.tsx
**Closes issue:** pb-17b (Subtask from [issue pb-17](https://toil.kitemaker.co/8rBVuP-Blank_AS/I4861q-Pizzabot/items/17))
**What's been done:**  Created a foundation for the admin panel followed the sketches from [Figma](https://www.figma.com/file/DigcxNodmOXgw69XPoKmtx/PB_landingPage?type=design&node-id=0-1&mode=design&t=EOmS2fpqjsiWFe6l-0). By now, only static data is implemented. 
**How to test:** Run next-frontend app and go to `localhost:4000/admin`
=> set up foundation for admin panel 

application/next-frontend/package-lock.json, application/next-frontend/package.json, application/next-frontend/pages/admin/index.tsx, application/next-frontend/pages/login/callback.tsx, application/next-frontend/pages/login/index.tsx, application/next-frontend/src/Admin/auth/index.ts, application/next-frontend/src/Admin/scenarios/Home/index.tsx, application/next-frontend/src/Admin/scenarios/SlackUsers.tsx, application/next-frontend/src/Admin/scenarios/Users.tsx, application/next-frontend/src/api/useSlackUsers.ts, application/next-frontend/src/api/useUsers.ts, application/next-frontend/src/api/utils.ts
- Imported SWR
- Created hook for fetching users from Slack workspace (+ loading/error handling)
- Working functionality for redirecting back to login if user's cookies expire
=> Slack users fetching

.github/workflows/test-versioning.yml, .github/workflows/versioning.yml, application/next-frontend/.eslintrc.json, application/next-frontend/.gitignore, application/next-frontend/build/.gitignore, application/next-frontend/next.config.js, infrastructure/main.tf, infrastructure/system/main.tf, infrastructure/system/variables.tf
Deploy the new nextjs frontend to production
=> Deploy new frontend

application/next-frontend/src/Admin/scenarios/SlackUsers.tsx, application/next-frontend/src/api/useAuthedSWR.ts, application/next-frontend/src/api/useRestaurants.ts, application/next-frontend/src/api/useSlackUsers.ts, application/next-frontend/src/api/utils.ts
Prøvd meg litt på å lage et greit oppsett for mutation forespørsler. Tror det ble helt greit, men er ikke helt stødig på SWR så mulig det står til stryk. Er en branch som heter mutation-reqs-demo som burde være plug and play hvis dere vil teste det.
=> Mutation reqs

application/next-frontend/package.json, application/next-frontend/src/Admin/components/CardComponent.tsx, application/next-frontend/src/Admin/scenarios/Events/index.tsx, application/next-frontend/src/Admin/scenarios/Home/index.tsx, application/next-frontend/src/Admin/scenarios/Restaurants/index.tsx, application/next-frontend/src/Admin/scenarios/SlackUsers.tsx, application/next-frontend/src/api/useAuthedSWR.ts, application/next-frontend/src/api/useSlackUsers.ts
Implements toggling of active properties on slack users
=> PB-30b: implements toggling active on workspace users

application/next-frontend/src/Admin/scenarios/Events/components/CreateEventCard.tsx, application/next-frontend/src/Admin/scenarios/Events/index.tsx, application/next-frontend/src/api/useEvents.ts
**Hva har blitt gjort?**
- Nå skal det gå an å poste og delete events der en random restaurant blir lagt til i eventet
**Hvordan teste?**
- Lag et pizza-arrangement for fremtiden og se det dukke opp under events
- Slett eventet
**Noe å merke seg**
- Det er ikke mulig å slette events som har passert. Fra den gamle frontenden så har event et felt som heter finalized, og jeg prøvde å bare vise events der finalized var false. Det så ikke ut til å fungere så det er noe jeg/vi må se på til senere :D
=> pb-35b/add functionality for posting and deleting events

application/next-frontend/src/Admin/scenarios/AdminMainPage.tsx, application/next-frontend/src/Admin/scenarios/Events/components/CreatePizzaEventCard.tsx, application/next-frontend/src/Admin/scenarios/Events/components/DeletePizzaEventCard.tsx, application/next-frontend/src/Admin/scenarios/Events/components/EventCalendar.tsx, application/next-frontend/src/Admin/scenarios/Events/components/PizzaEventModal.tsx, application/next-frontend/src/Admin/scenarios/Events/index.tsx
- PizzaEventModal, a modal which can use either of the cards to add/delete events
Posted events are not being shown, despite everything looking ok
- The database gives 201 codes
- I've tried to console log as far as possible - all the data seems to be carried all the way
- I've put the modal stuff outside the calendar, directly into AdminMainPage.tsx, the same thing happens
When deleting an event, a new one (probably previously added) pops up! Something is fishy and I'm struggling to find out what it is
Everything works as intended on Jacob's machine, so it's not unlikely that it's just my version of the bot that isn't complying
=> PB-39r: Integrating cards with calendar

application/next-frontend/src/Admin/components/AdminSidebar.tsx, application/next-frontend/src/Admin/components/Button.tsx, application/next-frontend/src/Admin/components/CardComponent.tsx, application/next-frontend/src/Admin/scenarios/Events/components/CreateEventCard.tsx, application/next-frontend/src/Admin/scenarios/Events/components/CreatePizzaEventCard.tsx, application/next-frontend/src/Admin/scenarios/Events/components/DeletePizzaEventCard.tsx, application/next-frontend/src/Admin/scenarios/Events/components/EventCalendar.tsx, application/next-frontend/src/Admin/scenarios/Events/index.tsx, application/next-frontend/src/Admin/scenarios/Navbar.tsx, application/next-frontend/src/Admin/scenarios/Onboarding/components/EventConfig.tsx, application/next-frontend/src/Admin/scenarios/Onboarding/components/RestaurantsConfig.tsx, application/next-frontend/src/Admin/scenarios/Onboarding/index.tsx, application/next-frontend/src/Landing/scenarios/FirstPage.tsx, application/next-frontend/src/styles/tailwindComposables.css, application/next-frontend/tailwind.config.ts
🧽✨✨ Styling cleanup
- La til fargene fra Figma i tailwind-config
- Endret til de fargene^ fra hardkodete farger i prosjektet
- Lagde en Button-komponent og endret til å bruke den de fleste steder
Gjerne test koden og sjekk at designet ikke har endret seg særlig mye fra sist!
=> Styling Cleanup

application/next-frontend/src/styles/globals.css
Fjerner bare darkmode css ting, da det ikke funker nå uansett, får legge det til igjen senere hvis man skal støtte det
=> PB-27m: fix; removes darkmode

application/next-frontend/pages/login/index.tsx, application/next-frontend/src/Landing/scenarios/Header/components/AddToSlackButton.tsx, application/next-frontend/src/Landing/scenarios/Header/index.tsx, application/next-frontend/src/Shared/components/LoginButton.tsx, application/next-frontend/tsconfig.json
=> feat: adds login button to landing page

application/next-frontend/src/Admin/scenarios/Onboarding/components/RestaurantsConfig.tsx
Legger til add knapp for å gjøre det klarere for brukere, enter trykk funker fortsatt.
=> Adding add button to make it more clear for users, enter still work

application/next-frontend/src/Admin/scenarios/Restaurants/components/NewRestaurantModal.tsx, application/next-frontend/src/Admin/scenarios/Restaurants/index.tsx
Prøvde meg først på å få til noe ala figmaen, men den var endel mer arbeid enn jeg så for meg så endte med å bare style den eksisterende modalen.
=> Style add restaurant modal

application/next-frontend/pages/index.tsx
To not confuse user during test with an out of date style
=> fix: remove old landing page for user test

application/next-frontend/src/Admin/scenarios/Events/components/EventCalendar.tsx
Instead of having colour "green-primary", the borders have the default light grey colour.
=> PB-47o: Put same colour on all borders in calendar

application/next-frontend/src/Admin/components/Button.tsx, application/next-frontend/src/Admin/scenarios/Events/components/CreatePizzaEventCard.tsx
adds configurable time for event. I have not implemented AM PM yet, scope for this pr i already big enough 
from:
to:
=> Pb-47b: configurable event time

application/next-frontend/package-lock.json, application/next-frontend/package.json, application/next-frontend/pages/_app.tsx, application/next-frontend/src/Admin/components/CardComponentWrapper.tsx, application/next-frontend/src/Admin/scenarios/AdminMainPage.tsx, application/next-frontend/src/Admin/scenarios/Events/components/EventCalendar.tsx, application/next-frontend/src/Shared/toast/defaultToast.tsx
Added a toaster when no restaurants are added if the user clicks on a date where there are no event
=> add toaster when no restaurants added

application/next-frontend/src/Admin/components/CardComponentWrapper.tsx, application/next-frontend/src/Admin/scenarios/Events/components/EventCalendarModal.tsx, application/next-frontend/src/Admin/scenarios/Events/index.tsx
Fixes infinite modals on eventmodal
=> Bugfix; infinite modals

application/next-frontend/src/Admin/components/CardComponentWrapper.tsx, application/next-frontend/src/Admin/scenarios/Events/components/EventCalendar.tsx, application/next-frontend/src/Admin/scenarios/Events/components/EventCalendarModal.tsx, application/next-frontend/src/Admin/scenarios/Events/index.tsx
Nå er Eventkortet og kalenderen samme høyde, både når det finnes arrangementer og ikke :D
=> make eventcalandar and events the same height

application/backend/app/api/crud/events.py, application/backend/app/api/crud/slack_users.py, application/backend/app/api/slack.py, application/backend/app/services/broker/schemas/get_slack_installation.py, application/backend/app/services/broker/schemas/new_slack_organization_event.py, application/backend/app/services/event_service.py, application/backend/app/services/slack_organization_service.py, application/backend/tests/api/test_slack.py, application/bot/src/api/bot_api.py, application/bot/src/broker/handlers/new_slack_organization.py, application/bot/src/broker/schemas/get_slack_installation.py, application/bot/src/broker/schemas/new_slack_organization_event.py, application/bot/src/slack/__init__.py, application/next-frontend/src/Admin/scenarios/Events/components/EventCalendar.tsx, application/next-frontend/src/Admin/scenarios/SlackChannel.tsx, application/next-frontend/src/api/useCurrentChannel.ts
[Kitemaker Ticket](https://toil.kitemaker.co/8rBVuP-Blank_AS/I4861q-Pizzabot/items/58)
Gjør egt akk det som kitemaker beskriver, men tror jeg venter med å refakturere velkommenmeldingen. 
Tror jeg har handlet de viktigste edge-casene, men med en safeguard på events slik at vi kan i allefall oppdage feil senere uten at noe breaker massivt.
=> PB-58: Bot dm's user instead of joining general

application/next-frontend/src/Landing/scenarios/FirstSection.tsx, application/next-frontend/src/Landing/scenarios/SecondSection.tsx, application/next-frontend/src/Landing/scenarios/ThirdSection.tsx
Tweaks sections 1, 2 and 3 to use better height props. Improves flex box usage somewhat for better scalability.
I recommend people who is going to review to checkout the branch themselves and test in their browser
no visible change
From:
To:
From:
To:
=> Pb-63: fix padding issue on sections

application/next-frontend/src/Landing/components/ImageWithPostit.tsx, application/next-frontend/src/Landing/scenarios/FifthSection.tsx, infrastructure/prod/system/main.tf, infrastructure/staging/system/main.tf
=> Pb-65: responsive fifth section

application/next-frontend/src/Admin/components/CardComponentWrapper.tsx, application/next-frontend/src/Admin/scenarios/AdminMainPage.tsx, application/next-frontend/src/Admin/scenarios/Events/components/CreatePizzaEventCard.tsx, application/next-frontend/src/Admin/scenarios/Events/components/DeletePizzaEventCard.tsx, application/next-frontend/src/Admin/scenarios/Events/components/EventCalendarModal.tsx, application/next-frontend/src/Admin/scenarios/Events/index.tsx, application/next-frontend/src/Admin/scenarios/Restaurants/components/NewRestaurantModal.tsx, application/next-frontend/src/Admin/scenarios/SlackChannel/components/SlackChannelModal.tsx, application/next-frontend/src/Admin/scenarios/SlackChannel/index.tsx, application/next-frontend/src/Shared/modal/ModalWrapper.tsx
-Admin panel sections divided into grid, and scales with screen width
-Tweaks modals to fit smaller screens
-Adds modal for slack-channel postit for consistancy
=> pb-67: admin page mobile friendly
